### Q1. Find out the differentiation of the following

In [1]:
#importing tensorflow
import tensorflow as tf

##### 1. Y = 5*x**2 + 6*x**4 for x = 0.5

In [2]:
x = tf.constant(0.5)
with tf.GradientTape() as t:
    t.watch(x)
    y = 5*x**2 + 6*x**4
    t.gradient(y,x)
    print(y)

tf.Tensor(1.625, shape=(), dtype=float32)


##### 2. Y = (1/23) * x**8 + 3*x**2 + 34 for x = 3.5

In [3]:
x = tf.constant(3.5)
with tf.GradientTape() as t:
    t.watch(x)
    y = (1/23) * x**8 + 3*x**2 + 34
    t.gradient(y,x)
    print(y)

tf.Tensor(1049.8263, shape=(), dtype=float32)


##### 3. Y = 45 + 34*x**2 + (1/2) *x for x = 2.8

In [4]:
x = tf.constant(2.8)
with tf.GradientTape() as t:
    y = 45 + 34*x**2 + (1/2) *x
    t.gradient(y,x)
    print(y)

tf.Tensor(312.96, shape=(), dtype=float32)


##### 4. Y = 34*x**12 + 23*x**4 + 4*x**4 + 2343 for x = 1.8

In [5]:
x = tf.constant(1.8)
with tf.GradientTape() as t:
    y=34*x**12 + 23*x**4 + 4*x**4 + 2343
    t.gradient(y,x)
    print(y)

tf.Tensor(41958.695, shape=(), dtype=float32)


##### 5. Y = (0.4) *x**23 + 2*x**(0.5) + 34 for x = 1.7

In [6]:
x = tf.constant(1.7)
with tf.GradientTape() as t:
    y=(0.4) *x**23 + 2*x**(0.5) + 34
    t.gradient(y,x)
    print(y)

tf.Tensor(79906.94, shape=(), dtype=float32)


### Q2.Find out the multiplication of the following


##### 1. A = 45, B = 34 and C = 12

In [7]:
A = tf.constant(45)
B = tf.constant(34)
C = tf.constant(12)
A*B*C

<tf.Tensor: shape=(), dtype=int32, numpy=18360>

##### 2. C = 33, B = 12 and Z = 12

In [8]:
C = tf.constant(33)
B = tf.constant(12)
Z = tf.constant(12)
C*B*Z

<tf.Tensor: shape=(), dtype=int32, numpy=4752>

### Q3.1 Create two random matrices with Normal distribution of length (3,4) and (4,3) and multiply the same.


In [9]:
X = tf.random.normal((3,4))
Y = tf.random.normal((4,3))
X,Y

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.49846202, -0.6672265 ,  0.69533354,  1.3602093 ],
        [-1.2137905 , -0.10874313,  1.1887078 ,  0.20200083],
        [-1.1280468 , -0.95292616,  0.36472958, -0.83636075]],
       dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 1.7620598 ,  1.4057044 , -1.4478678 ],
        [-1.3000592 , -0.5587838 , -0.805322  ],
        [-1.0852822 ,  1.7328259 , -1.4044678 ],
        [-0.43456018,  0.6589254 ,  1.1093004 ]], dtype=float32)>)

In [10]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.356612  ,  1.7733135 ,  1.7913464 ],
       [-3.375264  ,  0.54746044,  0.39955908],
       [-0.7812109 , -0.9723071 ,  0.96064854]], dtype=float32)>

### Q3.2 Dot Product: Create a random matrix with length (4,5) and multiply it with 5. (2 types).

In [11]:
Z = tf.random.uniform((4,5))
Z

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.6430154 , 0.14249778, 0.7611245 , 0.7855327 , 0.9200218 ],
       [0.9549148 , 0.03170538, 0.79516494, 0.00499117, 0.78452706],
       [0.89934707, 0.02479601, 0.7490182 , 0.2599553 , 0.5753714 ],
       [0.5909822 , 0.8327813 , 0.13834822, 0.863978  , 0.6724932 ]],
      dtype=float32)>

In [12]:
#1st method
tf.constant(5.0)*Z

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[3.215077  , 0.7124889 , 3.8056226 , 3.9276636 , 4.600109  ],
       [4.7745743 , 0.1585269 , 3.9758248 , 0.02495587, 3.9226353 ],
       [4.4967356 , 0.12398005, 3.745091  , 1.2997764 , 2.8768568 ],
       [2.954911  , 4.1639066 , 0.6917411 , 4.31989   , 3.362466  ]],
      dtype=float32)>

In [13]:
#2nd method
tf.tensordot(Z,tf.constant(5.0),axes=0)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[3.215077  , 0.7124889 , 3.8056226 , 3.9276636 , 4.600109  ],
       [4.7745743 , 0.1585269 , 3.9758248 , 0.02495587, 3.9226353 ],
       [4.4967356 , 0.12398005, 3.745091  , 1.2997764 , 2.8768568 ],
       [2.954911  , 4.1639066 , 0.6917411 , 4.31989   , 3.362466  ]],
      dtype=float32)>